plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'ru.aroundme'
version = '0.0.1-SNAPSHOT'
description = 'countries'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-flyway'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    annotationProcessor "org.projectlombok:lombok:1.18.42"
    compileOnly 'org.projectlombok:lombok:1.18.42'
    runtimeOnly 'org.postgresql:postgresql:42.7.3'
    implementation 'org.flywaydb:flyway-database-postgresql:11.19.1'
}

tasks.named('test') {
    useJUnitPlatform()
}
